### ISSUE TITLE
Please also style JSXC app

### ISSUE THREAD

**Issue by poVoq** [mwalbeck/nextcloud-breeze-dark#113]
**Which app would you like to have styled**:
https://apps.nextcloud.com/apps/ojsxc
Right now JSXC is very difficult to use with this dark theme due to text color issues.

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.3

Thanks!

**Comment by mwalbeck** [comment]
Hi,

Oh, I didn't notice it got updated to support NC18, thanks for letting me know. I'll have a look and see what I can do.

**Comment by mwalbeck** [comment]
I have merged the styling to master and will release it a bit later today. I didn't have time to test/style audio/video calls but everything else should be good. Do let me know if you find any issues.

**Comment by poVoq** [comment]
The text of the messages in MUCs (but not 1:1 chats) still appears as light grey text on white background. Almost not readable.

**Comment by mwalbeck** [comment]
> The text of the messages in MUCs (but not 1:1 chats) still appears as light grey text on white background. Almost not readable.
> Edit: The button for loading more archived messages if you scroll up is also still colored like that.

Thanks for letting me know, I'll get them fixed

> Edit2: Icons in the hamburger menu are also black on dark grey background.

That's embarrassing, I completely forgot about those...

**Comment by mwalbeck** [comment]
@poVoq I've realised that MUC's arent supported by the internal xmpp server and I had a few problems registering for a managed one. If you could provide an image of the issue and the css class name of the text messages in an MUC, then that would be a big help.

**Comment by mwalbeck** [comment]
@poVoq nevermind, third time really is the charm I guess.

**Comment by mwalbeck** [comment]
It should hopefully be all good now. Latest fixes will be in 18.0.14, hopefully out tomorrow-

**Comment by poVoq** [comment]
Almost there. The only thing missing I think is the account settings button next to the account name under settings. Currently it is invisible with this dark theme.

**Comment by mwalbeck** [comment]
Could you post a screenshot? I can't seem to find the button you are referring to.

**Comment by poVoq** [comment]
Heh, never mind, I just realized that the button is now invisible in the default JSXC as well. Sorry for the false alarm.

**Comment by mwalbeck** [comment]
No worries
