### ISSUE TITLE
Button visibility in Talk

### ISSUE THREAD

**Issue by Valdnet** [mwalbeck/nextcloud-breeze-dark#268]
Steps:

1. Open the Talk application.
2. Select a conversation.
3. Select the settings for the conversation.

Button is missing for function "Leave conversation".

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47037905/130241401-e1bec185-3eec-42fb-9dfb-4459512dd9f6.png)

**Setup (please complete the following information):**

-   Nextcloud version: 22.1.0
-   Theme version: 22.0.1
-   Browser and browser version: Firefox 91.0.1

**Comment by mwalbeck** [comment]
Thanks for reporting! It'll be fixed in the next released!

**Comment by Valdnet** [comment]
@mwalbeck After the changes, the function button still does not appear. Can you check?

**Comment by mwalbeck** [comment]
@Valdnet It works, the fix just hasn't been released yet, but it'll be included in the next release of the theme.

**Comment by Valdnet** [comment]
> After the changes

@mwalbeck I found it only works when the language is set to English:

![obraz](https://user-images.githubusercontent.com/47037905/130792101-866b756b-6f4a-4c99-bb75-4a61fd843211.png)

When you change to another language the button is still not displayed:

![obraz](https://user-images.githubusercontent.com/47037905/130791976-15945bd8-b901-4c83-a9a2-a602958a1461.png)

![obraz](https://user-images.githubusercontent.com/47037905/130791835-469554d5-c5cc-4b72-be99-47059b63785b.png)

I wonder why this is happening.

**Comment by mwalbeck** [comment]
Ohh... I can see the CSS Id is also localised for some reason, so when you change the language, the CSS id of the section where the button is, also changes.

I'll have to apply the styling some other way then

**Comment by Valdnet** [comment]
> I can see the CSS Id is also localised for some reason, so when you change the language, the CSS id of the section where the button is, also changes.

Exactly. I noticed it too 😉.
