### ISSUE TITLE
Fix white background in logging

### ISSUE THREAD

**Issue by irule311** [mwalbeck/nextcloud-breeze-dark#7]
When expanding a logged item, there it a white background.
![capture](https://cloud.githubusercontent.com/assets/10052885/25599937/99fa4488-2ea5-11e7-8c6a-448498e389d7.PNG)

This should fix it:
`._3UrpHQRjyb138CVLZNW1LL tr._3LRdZBXEOn3DskYBRJfpbZ{
	background-color: #31363b;
}`

I didn't submit a pull request because I wasn't sure about the sass code, but this is the css that fixes it.

**Comment by mwalbeck** [comment]
Can try and update the theme, this problem should already have been fixed

**Comment by irule311** [comment]
No, it hasn't been fixed yet. I just tried updating and the problem is still there. If there is a longer log or if you click on a log item, the background turns white making it unreadable. I just tested the css I provided again, and it works great.

I would assume you just need to add it into the sass code and recompile it?

**Comment by mwalbeck** [comment]
I will look more into it. I currently don't have the problem on my end which is why I asked you to update.

**Comment by mwalbeck** [comment]
Found the issue and have pushed a fix to master.
