### ISSUE TITLE
Custom background does not display

### ISSUE THREAD

**Issue by ToneLune** [mwalbeck/nextcloud-breeze-dark#87]
Hello,

I continue to use this beautiful development for many versions, and I am very happy to see it appear directly in the NextCloud applications. Thank you !

Unless I am mistaken, it is no longer possible to use a personalized background. The background from /core/img/background.png is displayed instead of the one chosen in the personalization settings.

By deactivating Breeze Dark application, personalized background appears well.
It looks like an old issue: https://github.com/mwalbeck/nextcloud-breeze-dark/issues/11

Good evening (at least from here) !

**Comment by mwalbeck** [comment]
Hi,

I'm assuming from your description that you are using the app version of the theme, and just to make sure, have you set the personalized background with the Theming app? The intention was at least that it was suppose to work.

Could you share your Nextcloud version and the theme version, then I'll gladly look more into it.

**Comment by ToneLune** [comment]
NextCloud version : 18.0.0
Breeze Dark version : 18.0.2
I tried with version 18.0.3 which has just been pushed, same result.

I only go through the NextCloud> Theming settings

I tried to Reset to default in Login image, here is the image that appears in the background login page:
![background](https://user-images.githubusercontent.com/12959697/73701497-0fd30280-46ea-11ea-8800-84612301dc82.png)

When I upload my own background, the above image is always displayed but with a zoom effect.

Thank you for this quick response !

**Comment by mwalbeck** [comment]
Thanks for the info. This is cause by me wanting a dark background but also trying to preserve the new default background-image. I'll see if I can't find a better way to do it, which allows custom backgrounds through the theming app.

**Comment by ToneLune** [comment]
Glad to hear it's not my fault, for once. : P

**Comment by mwalbeck** [comment]
It should be fixed with the new 18.0.4 release. Let me know if there are any problems.

**Comment by eriteric** [comment]
I am getting this issue still with Nextcloud 18.0.2 and Breeze-theme 18.0.9 added through the nextcloud app interface.

**Comment by mwalbeck** [comment]
@eriteric I had a quick look and custom backgrounds are still working as intended on my instance. If I could get you to open a new issue and describe your exact problem in a bit more details, then I'll be happy to take a closer look.

**Comment by thefactremains** [comment]
I'm still seeing this issue, but ONLY when I check `Enable Breeze Dark theme by default`

![CleanShot 2020-10-22 at 12 53 16](https://user-images.githubusercontent.com/20331166/96923055-9476d400-1465-11eb-82ec-87992cda5144.png)

**Comment by mwalbeck** [comment]
@thefactremains Have a look at this comment https://github.com/mwalbeck/nextcloud-breeze-dark/issues/174#issuecomment-711152725 there are 2 workarounds that will hopefully help
